verbatim:
  cabal-version: 2.4

name: pirouette
version: 2.0.0
extra-source-files:
  - LICENSE
  - README.md

dependencies:
  - ansi-terminal
  - base >= 4.9 && < 5
  - data-default
  - mtl >= 2.2.2
  - interpolate
  - bytestring
  - containers
  - extra
  - text
  - prettyprinter
  - megaparsec
  - parser-combinators
  - uniplate
  - deriving-compat
  - template-haskell
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - tasty-expected-failure
  - QuickCheck
  - haskell-stack-trace-plugin
  - parallel
  - optics-core
  - optics-th
  # PureSMT deps
  - process
  - typed-process
  - deepseq
  - timestats

library:
  source-dirs: src
  ghc-options:
    -Wall
    -Wno-orphans

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests/unit
    dependencies:
      - pirouette
    ghc-options:
      -threaded

executables:
  example:
    main: Main.hs
    source-dirs:
      - src/
    dependencies:
      - pirouette
    ghc-options:
      -O3
