verbatim:
  cabal-version: 2.4

name: pirouette
version: 2.0.0
extra-source-files:
  - LICENSE
  - README.md

dependencies:
  - ansi-terminal
  - base >= 4.9 && < 5
  - data-default
  - mtl >= 2.2.2
  - interpolate
  - bytestring
  - containers
  - extra
  - text
  - prettyprinter
  - megaparsec
  - parser-combinators
  - uniplate
  - deriving-compat
  - template-haskell
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - tasty-expected-failure
  - QuickCheck
  - haskell-stack-trace-plugin
  - parallel
  - optics-core
  - optics-th
  - raw-strings-qq
  - transformers
  # PureSMT deps
  - smtlib-backends >=0.3 && <0.4
  - smtlib-backends-z3 >=0.3 && <0.4

library:
  source-dirs: src
  ghc-options:
    -Wall
    -Wno-orphans

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests/unit
    dependencies:
      - pirouette
    ghc-options:
      -threaded

## executables:
##   spec-prof:
##     main: Spec.hs
##     source-dirs:
##       - tests/unit
##     dependencies:
##       - pirouette
##     ghc-options:
##       -threaded
##       -fprof-auto
##       -fexternal-interpreter
##       "-with-rtsopts=-N -p -s -h"
