verbatim:
  cabal-version: 2.4

name: pirouette
version: 0.0.0
extra-source-files:
  - LICENSE
  - README.md

dependencies:
  - base >= 4.9 && < 5
  - mtl >= 2.2.2
  - bytestring
  - containers
  - lens
  - text
  - prettyprinter
  - gitrev
  - optparse-applicative
  - parsec
  - megaparsec
  - uniplate
  - hspec
  - QuickCheck
  - bound
  - interpolate
  - deriving-compat
  - simple-smt
  - process
  - tlaplus
  - tlaplus-qq
  - flat >= 0.4.5
  - plutus-core
  - unbound-generics
  - unification-fd

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: executable
  dependencies:
    - pirouette

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests/unit
    dependencies:
      - pirouette
