verbatim:
  cabal-version: 2.4

name: pirouette
version: 0.0.0
extra-source-files:
  - LICENSE
  - README.md

dependencies:
  - base >= 4.9 && < 5
  - aeson
  - mtl >= 2.2.2
  - bytestring
  - containers
  - lens
  - text
  - prettyprinter
  - gitrev
  - optparse-applicative
  - megaparsec
  - parser-combinators
  - uniplate
  - hspec
  - QuickCheck
  - interpolate
  - deriving-compat
  - simple-smt
  - process
  - tlaplus
  - tlaplus-qq
  - flat >= 0.4.5
  - plutus-core
  - list-t
  - template-haskell
  - tasty
  - tasty-hunit
  - tasty-hspec
  - tasty-quickcheck
  - tasty-expected-failure
  - haskell-stack-trace-plugin
  - optics-core
  - optics-th
  - ansi-terminal

library:
  source-dirs: src
  ghc-options:
    -Wall
    -Wno-orphans
    -fplugin=StackTrace.Plugin

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests/unit
    dependencies:
      - pirouette
