name: Install nix with cached nix env
description: Install nix and attempts to retrieve /nix/store from a cache
runs:
  using: "composite"
  steps:
  - name: Create /nix/store with liberal permissions
    run: |
        # Create with liberal rights, otherwise cache action will complain
        # about permission errors.
        sudo mkdir -p /nix/store
        sudo chmod -R 777 /nix
    shell: bash

  - name: Cache nix env
    uses: actions/cache@v2
    with:
      path: |
        # See https://github.com/actions/cache/pull/726
        /nix/store/**
        # Missing something?
        /nix/var/nix/*/*
        /nix/var/nix/db/*
        /nix/var/nix/db/*/**
        !/nix/var/nix/daemon-socket/socket
        !/nix/var/nix/userpool/*
        !/nix/var/nix/gc.lock
        !/nix/var/nix/db/big-lock
        !/nix/var/nix/db/reserved
      key: ${{ runner.os }}-nix-cache-${{ hashFiles('**/.nix') }}
      restore-keys: |
      ${{ runner.os }}-nix-cache

  - name: Install nix
    uses: cachix/install-nix-action@v15
    with:
      nix_path: nixpkgs=channel:nixos-unstable

